#!/bin/bash

env_init=(
"/opt/offline/slc7_amd64_gcc900/external/fasthadd/2.3-ljfedo5"
"/opt/offline/cc8_amd64_gcc9/external/fasthadd/2.3-ljfedo5"
"/opt/offline/slc7_amd64_gcc900/external/fasthadd/2.3-ghbfee11"
"/opt/offline/slc7_amd64_gcc820/external/fasthadd/2.3-bcolbf7"
)

for env in "${env_init[@]}"; do
         test -d "$env" || continue

         source "$env/etc/profile.d/init.sh"
         exec "$env/bin/fastHadd" "$@"


         exit # unreachable
done

echo "fastHadd not found, make sure external+fasthadd rpm is installed (via cmsdist)"
exit 1
