#!/bin/bash

env_init=(
"/opt/offline/slc7_amd64_gcc900/lcg/root/6.22.08-ljfedo"
"/opt/offline/cc8_amd64_gcc9/lcg/root/6.22.08-ljfedo"
"/opt/offline/slc7_amd64_gcc900/lcg/root/6.22.06"
"/opt/offline/slc7_amd64_gcc820/lcg/root/6.20.06-bcolbf"
)

for env in "${env_init[@]}"; do
         test -d "$env" || continue

         source "$env/etc/profile.d/init.sh"
         exec "$env/bin/hadd" "$@"


         exit # unreachable
done

echo "hadd not found, make sure external+fasthadd rpm is installed (via cmsdist)"
exit 1
