#!/bin/bash

env_init=(
"/opt/offline/slc7_amd64_gcc700/lcg/root/6.14.09-pafccj"
)

for env in "${env_init[@]}"; do
         test -d "$env" || continue

         source "$env/etc/profile.d/init.sh"
         exec "$env/bin/hadd" "$@"


         exit # unreachable
done

echo "hadd not found, make sure external+fasthadd rpm is installed (via cmsdist)"
exit 1
