#!/bin/bash

env_init=(
"/opt/offline/el8_amd64_gcc11/lcg/root/6.26.11-fec5b250e1cd56b91a094709de26e5b8"
"/opt/offline/slc7_amd64_gcc11/lcg/root/6.26.11-fec5b250e1cd56b91a094709de26e5b8"
"/opt/offline/slc7_amd64_gcc900/lcg/root/6.22.08-ljfedo"
)

for env in "${env_init[@]}"; do
         test -d "$env" || continue

         source "$env/etc/profile.d/init.sh"
         exec "$env/bin/hadd" "$@"


         exit # unreachable
done

echo "hadd not found, make sure external+fasthadd rpm is installed (via cmsdist)"
exit 1
